services:
  - type: web
    name: sres-laravel
    env: docker
    plan: free
    repo: https://github.com/Cids08/figma
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sres-mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sres_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ""
